---
- name: Testar conectividade com RDS MySQL
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Verificar conexão com o banco de dados MySQL
      mysql_db:
        login_host: "rds-mack-useast1-alu1.cegqxepnhyuc.us-east-1.rds.amazonaws.com"
        login_user: "admin"
        login_password: "senha123"
        name: "information_schema" 
      register: result

    - name: Exibir resultado da conexão
      debug:
        msg: "Conexão com RDS MySQL bem-sucedida!"
      when: result.changed

    - name: Consultar dados na tabela
      mysql_query:
        login_host: "rds-mack-useast1-alu1.cegqxepnhyuc.us-east-1.rds.amazonaws.com"
        login_user: "admin"
        login_password: "senha123"
        login_db: "dbAlunosIac"
        query: "SELECT * FROM tb_register"
      register: query_result
