---
- name: Provisionar instâncias na AWS
  hosts: localhost
  vars:
    ansible_python_interpreter: "/usr/bin/python3.9"
  tasks:
 - name: Open port 80 in the security group
   ec2_group:
     name: default
     region: us-east-1
     rules:
       - proto: tcp
         from_port: 80
         to_port: 80
         cidr_ip: 0.0.0.0/0
     aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
     aws_secret_access_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
   register: update_sg

  - name: Provisionar instância EC2 para o servidor web
    amazon.aws.ec2_instance:
      name: "web-server-1"
      key_name: "2505key"
      region: us-east-1
      instance_type: t2.micro
      security_group: default
      network:
        assign_public_ip: true
        vpc_subnet_id: subnet-0ef28efe8293628c4
      image_id: ami-0fe630eb857a6ec83
      tags:
        Environment: Testing
    register: ec2_remote_facts


  - name: Adicionar IP ao grupo específico no arquivo ansible/hosts
    lineinfile:
      path: /etc/ansible/hosts
      insertafter: web-servers
      line: "web-server-1 ansible_host={{ item.public_ip_address }}"
      state: present
    with_items: "{{ ec2_remote_facts.instances }}"
    delegate_to: localhost
    become: yes
