---
- name: Clonar repositório Git e copiar conteúdo para servidor web
  hosts: web-server-1
  tasks:
    - name: Criar diretório do repositório no servidor
      file:
        path: /tmp/repo
        state: directory

    - name: Instalar git
      become: true
      yum:
        name: git
        state: present
      when: ansible_os_family == 'RedHat'  # Ajuste conforme o sistema operacional do servidor

    - name: Clonar repositório Git
      git:
        repo: https://github.com/anisioajr/web-app-ajr.git
        dest: /tmp/repo  # Diretório de destino no servidor

    - name: Copiar conteúdo do repositório para o diretório do servidor web
      copy:
        src: /tmp/repo/
        dest: /var/www/html  
        remote_src: true

    - name: Remover arquivos do diretório do repositório após reiniciar o Apache
      file:
        path: /tmp/repo
        state: absent
  handlers:
    - name: restart apache
      become: true
      service:
        name: httpd
        state: restarted
