---
- name: Instalação de dependências
  hosts: localhost
  become: true
  tasks:
    - name: Instalar git
      dnf:
        name: git
        state: present
    
    - name: Install Unzip
      yum:
        name: unzip
        state: present

    - name: Instalar Python 3.9 e pip
      dnf:
        name: python3.9-pip
        state: present

    - name: Instalar boto3 e botocore usando pip3.9
      pip:
        name: "{{ item }}"
        executable: pip3.9
      loop:
        - boto3
        - botocore

    - name: Instalar Ansible Core
      dnf:
        name: ansible-core
        state: present

    - name: Baixar AWS CLI
      command: "curl -o awscliv2.zip https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
      args:
        chdir: "{{ ansible_env.HOME }}"
      become: yes

    - name: Extrair AWS CLI
      command: "unzip -o awscliv2.zip"
      args:
        chdir: "{{ ansible_env.HOME }}"
      become: yes

    - name: Instalar AWS CLI
      command: "./aws/install --update"
      args:
        chdir: "{{ ansible_env.HOME }}"
      become: yes

    - name: instalar galaxy
      command: "ansible-galaxy collection install amazon.aws"
      args:
        chdir: "{{ ansible_env.HOME }}"
      become: yes

    - name: instalar galaxy
      command: "ansible-galaxy collection install community.postgresql"
      args:
        chdir: "{{ ansible_env.HOME }}"
      become: yes
      
    - name: Add ansible-servers group to hosts file
      lineinfile:
        path: /etc/ansible/hosts
        line: "[ansible-servers]"
        create: yes
        state: present
      notify: Insert ansible1 to ansible-servers

    - name: Add web-servers group to hosts file
      lineinfile:
        path: /etc/ansible/hosts
        line: "[web-servers]"
        state: present

    - name: Add db-servers group to hosts file
      lineinfile:
        path: /etc/ansible/hosts
        line: "[db-servers]"
        state: present

  handlers:
    - name: Insert ansible1 to ansible-servers
      lineinfile:
        path: /etc/ansible/hosts
        insertafter: "ansible-servers"
        line: "ansible1 ansible_host=localhost"

