---
- name: Instalação de dependências
  hosts: localhost
  become: true
  tasks:
    - name: Install Unzip
      yum:
        name: unzip
        state: present

    - name: Instalar Python 3.9 e pip
      dnf:
        name: python3.9-pip
        state: present

    - name: Criar diretório /opt/webhook
      file:
        path: /opt/webhook
        state: directory
        mode: '0755'

    - name: Criar diretório /etc/systemd/system/
      file:
        path: /etc/systemd/system/
        state: directory
        mode: '0755'
        
    - name: Instalar flask, boto3 e botocore usando pip3.9
      pip:
        name: "{{ item }}"
        executable: pip3.9
      loop:
        - ansible
        - flask
        - boto3
        - botocore

    - name: Baixar AWS CLI
      command: "curl -o awscliv2.zip https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
      args:
        chdir: "{{ ansible_env.HOME }}"
      become: yes

    - name: Extrair AWS CLI
      command: "unzip -o awscliv2.zip"
      args:
        chdir: "{{ ansible_env.HOME }}"
      become: yes

    - name: Instalar AWS CLI
      command: "./aws/install --update"
      args:
        chdir: "{{ ansible_env.HOME }}"
      become: yes

    - name: instalar galaxy
      command: "ansible-galaxy collection install amazon.aws"
      args:
        chdir: "{{ ansible_env.HOME }}"
      become: yes

    - name: instalar galaxy
      command: "ansible-galaxy collection install community.mysql"
      args:
        chdir: "{{ ansible_env.HOME }}"
      become: yes
      
    - name: Add ansible-servers group to hosts file
      lineinfile:
        path: /etc/ansible/hosts
        line: "[ansible-servers]"
        create: yes
        state: present
      notify: Insert ansible1 to ansible-servers

    - name: Add web-servers group to hosts file
      lineinfile:
        path: /etc/ansible/hosts
        line: "[web-servers]"
        state: present

    - name: Add db-servers group to hosts file
      lineinfile:
        path: /etc/ansible/hosts
        line: "[db-servers]"
        state: present
        
    - name: Copiar arquivo webhook.py para /opt/webhook
      copy:
        src: /root/ansible-project/webhook.py
        dest: /opt/webhook/webhook.py
        owner: root
        group: root
        mode: '0644'
        
    - name: Copiar arquivo webhook.service para /etc/systemd/system/webhook.service
      copy:
        src: /root/ansible-project/webhook.service
        dest: /etc/systemd/system/webhook.service
        owner: root
        group: root
        mode: '0644'

    - name: Recarregar o daemon do systemd
      command: systemctl daemon-reload

    - name: Habilitar o serviço webhook
      systemd:
        name: webhook.service
        enabled: yes

    - name: Iniciar o serviço webhook
      systemd:
        name: webhook.service
        state: started

    - name: Instalar iptables-services
      yum:
        name: iptables-services
        state: present

    - name: Habilitar o serviço iptables
      systemd:
        name: iptables
        enabled: yes

    - name: Iniciar o serviço iptables
      systemd:
        name: iptables
        state: started

    - name: Adicionar regra para aceitar tráfego TCP na porta 80
      command: iptables -I INPUT -p tcp --dport 80 -j ACCEPT

    - name: Salvar as regras do iptables
      command: service iptables save
      
  handlers:
    - name: Insert ansible1 to ansible-servers
      lineinfile:
        path: /etc/ansible/hosts
        insertafter: "ansible-servers"
        line: "ansible1 ansible_host=localhost"
        state: present

        

